Bug Fixes and Reorder arrays
SpakowitzLab/wlcsim pull request #32
Opened 2017-08-03 22:19 UTC by qmacAstanford

Reorder R(NT,3) to R(3,NT) because I usually access x,y,z in succession.
Also make several Bug Fixes that probably only affect me.

2017-08-09 21:54 UTC, brunobeltran requested changes
recommend cof and cofMtrx renamed to coefs in src/wlcsim/MCparrll_mpi.f90 and src/wlcsim/wlcsim_quinn.f03.

all changes minor, except one bug in BD. 

Accepted for merge with these changes.

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_confine.f03
>              ECon = 9990000.0_dp
We should make this large energy a constant. And while we're at it, we should do this for all "just put a big energy here" numbers.

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MCsim.f03
> +    integer m_plus3
comment that this "m" is a spherical harmonic quantum "m"

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_int_swap.f03
> +integer m_plus3
same

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_int_rep.f03
> +integer m_plus3
same

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_int_chem.f03
> +integer m_plus3
same

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/Y2calc.f03
> +real(dp), parameter, dimension(5) :: coefficient = (/1.092548430592079, &
replace with symbolic values

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/verifyEnergiesFromScratch.f03
> +    if(abs(wlc_d%EBind-wlc_d%DEBind) > 0.00001) then
replace with hardcoded float eps in params

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/verifyEnergiesFromScratch.f03
> +    if(abs((wlc_d%EElas(1) +  wlc_d%EElas(2) + wlc_d%EElas(3))-&
replace with hardcoded float eps in params

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/verifyEnergiesFromScratch.f03
> +        if(abs(wlc_d%EChi-wlc_d%DEChi) > 0.0001_dp) then
replace with hardcoded float eps in params

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/verifyEnergiesFromScratch.f03
> +        if(abs(wlc_d%ECouple-wlc_d%DECouple) > 0.0001_dp) then
replace with hardcoded float eps in params

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/verifyEnergiesFromScratch.f03
> +        if(abs(wlc_d%EKap-wlc_d%DEKap) > 0.0001_dp) then
replace with hardcoded float eps in params

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/verifyEnergiesFromScratch.f03
> +        if(abs(wlc_d%EField-wlc_d%DEField) > 0.00001) then
replace with hardcoded float eps in params

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/verifyEnergiesFromScratch.f03
> +            if(abs(wlc_d%EMaiersaupe-wlc_d%deMaierSaupe) > 0.00001) then
replace with hardcoded float eps in params

2017-08-09 21:54 UTC, brunobeltran commented on src/util/binning.f03
>          real(dp), parameter :: eps = 0.00000001
should inherit from params instead

2017-08-09 21:54 UTC, brunobeltran commented on src/util/getdim.f03
> +     RCOM(:,IP) = SUM(X,DIM = 1)/REAL(N)
dim should have changed

2017-08-09 21:54 UTC, brunobeltran commented on src/wlcsim/MCparrll_mpi.f90
>      if (abs(wlc_d%EChi-x(1)*CofOld(1)).gt.0.0000001_dp) then
immediately unpack arr and do things with names
for x and cof

2017-08-09 21:54 UTC, brunobeltran commented on src/wlcsim/MCparrll_mpi.f90
>      if (abs(wlc_d%EChi-x(1)*CofOld(1)).gt.0.0000001_dp) then
params eps again

2017-08-09 21:54 UTC, brunobeltran commented on src/wlcsim/MCparrll_mpi.f90
>      if (abs(wlc_d%EChi-x(1)*Cof(1)).gt.0.000001_dp) then
params eps again

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_move.f90
> -      if (abs(RP(IT1,1)-R(IT1,1)).gt.0.000001) then
params eps

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_move.f90
> +      if (abs(RP(1,IT1)-R(1,IT1)).gt.0.000001) then
params eps

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_move.f90
> -      if (abs(RP(IT2,1)-R(IT2,1)).gt.0.000001) then
params eps

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_move.f90
>            if (abs(d1-d2).gt.0.000001) then
params eps

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_move.f90
>        -(drNew(1)**2 + drNew(2)**2 + drNew(3)**2)).gt.0.000001) then
params eps

2017-08-09 21:54 UTC, brunobeltran commented on src/mc/MC_move.f90
>        -(drPerpNew(1)**2 + drPerpNew(2)**2 + drPerpNew(3)**2)).gt.0.000001_dp) then
params eps

2017-08-09 21:54 UTC, brunobeltran commented on src/wlcsim/params.f03
> +        wlc_p%KAP =0.0_dp ! "fairly" incompressible --Quinn
no longer "fairly" incompressible lol

2017-08-09 21:54 UTC, brunobeltran commented on src/wlcsim/params.f03
> +        print*, " 1/number of kuhn lengths between beads, eps ", wlc_p%eps
nope, was correct as-was

2017-08-09 21:54 UTC, brunobeltran commented on src/wlcsim/params.f03
> -            allocate(wlc_d%RP(NT,3))
these can be pulled out of the if statement now actually, can we do that here? thanks!

2017-08-10 04:17 UTC, qmacAstanford commented on src/wlcsim/params.f03
> -            allocate(wlc_d%RP(NT,3))
I always need RP but I don't know if you do when you are only doing bd.  I'll let you make that call.

2017-08-10 09:17 UTC, qmacAstanford commented on src/mc/verifyEnergiesFromScratch.f03
> +    if(abs((wlc_d%EElas(1) +  wlc_d%EElas(2) + wlc_d%EElas(3))-&
fixed

2017-08-10 09:17 UTC, qmacAstanford commented on src/mc/MC_int_swap.f03
> +integer m_plus3
fixed

2017-08-10 09:20 UTC, qmacAstanford commented on src/mc/Y2calc.f03
> +real(dp), parameter, dimension(5) :: coefficient = (/1.092548430592079, &
fixed as much as I can.  Replaced with locally defined PI.  Can't used pi from params as it isn't a parameter

2017-08-10 20:14 UTC, brunobeltran approved these changes

2017-08-10 20:15 UTC, brunobeltran commented
I am able to compile the code using params::pi in definition of constants. We should clear this up then merge these changes!

2017-08-11 00:14 UTC, merged